
services:
  api:
    build: .
    container_name: fastapi_app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    # The default command in Dockerfile runs the Uvicorn server
    # volumes:    # (Optional) mount code for live reload in development
    #   - .:/code

  worker:
    build: .
    container_name: celery_worker
    env_file: .env
    depends_on:
      - db
      - redis
    command: celery -A app.tasks.celery_app worker --loglevel=info
    

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-multitenant}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
      MYSQL_USER: ${DB_USER:-appuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-apppass}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# Named volumes for persistent data
volumes:
  db_data:
  redis_data:
